name: Build and Compile System Service Hook

on:
  push:
    branches:
      - main   # 当推送到 main 分支时触发构建
  pull_request:
    branches:
      - main   # 当提交 pull request 到 main 分支时触发构建

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 虚拟机

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 获取仓库代码

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Set up Android SDK
      run: |
        # 安装 Android SDK 工具
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d $HOME/Android
        rm sdk-tools.zip
        echo "y" | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
        $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Install Maven dependencies
      run: |
        # 安装项目依赖
        mvn install -DskipTests

    - name: Install Android dependencies
      run: |
        # 安装 Android 构建所需的依赖项
        sudo apt-get install -y openjdk-8-jdk
        export ANDROID_HOME=$HOME/Android
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
        mvn install

    - name: Build project with Maven
      run: |
        # 构建项目并执行 Maven 编译
        mvn clean compile

    - name: Build APK or System Service Hook
      run: |
        # 如果这是一个 APK 构建或系统服务钩子构建，确保路径是正确的
        mvn clean package -DskipTests

